import { db } from '@/lib/db';
import { generatedMockups } from '@/lib/db/schema';
import { desc } from 'drizzle-orm';
import Link from 'next/link';
import { PageHeader, Card, EmptyState } from '@/components/ui';
import { Sparkles, ImageIcon } from 'lucide-react';
import { formatDistanceToNow } from 'date-fns';

export const dynamic = 'force-dynamic';

export default async function MockupsPage() {
  const list = await db.query.generatedMockups.findMany({
    orderBy: [desc(generatedMockups.createdAt)],
    with: { template: true, generatedBy: true },
    limit: 60,
  });

  return (
    <div className="p-8 max-w-7xl">
      <PageHeader
        title="Generated Mockups"
        subtitle={`${list.length} mockup${list.length === 1 ? '' : 's'} generated by the agent.`}
        action={
          <Link href="/mockups/new" className="btn-primary">
            <Sparkles size={16} /> Generate New
          </Link>
        }
      />

      {list.length === 0 ? (
        <EmptyState
          icon={<ImageIcon size={32} />}
          title="No mockups generated yet"
          description="Pull a job from HQ Print and generate a client-ready mockup using Craft's house templates."
          action={<Link href="/mockups/new" className="btn-primary"><Sparkles size={16} /> Generate Your First</Link>}
        />
      ) : (
        <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
          {list.map(m => (
            <Card key={m.id} className="p-3">
              <div className="aspect-square bg-[#0A0A0A] rounded border border-[#2A2A2A] mb-3 flex items-center justify-center">
                <ImageIcon size={32} className="text-gray-700" />
              </div>
              <div className="text-sm font-medium truncate">{m.template.name}</div>
              <div className="text-xs text-gray-500">{m.garmentColor}</div>
              <div className="text-[10px] text-gray-600 mt-2">
                {formatDistanceToNow(m.createdAt, { addSuffix: true })}
                {m.generatedBy && ` · ${m.generatedBy.name}`}
              </div>
            </Card>
          ))}
        </div>
      )}
    </div>
  );
}
